// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MAIN_MENU_H
#define UI_MAIN_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_main_menu
extern void ui_main_menu_screen_init(void);
extern void ui_main_menu_screen_destroy(void);
extern lv_obj_t * ui_main_menu;
extern lv_obj_t * ui_Image1;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

